spring:
  datasource:
    url: jdbc:mysql://rm-8vb31hkbk62yx45p3co.mysql.zhangbei.rds.aliyuncs.com:23306/erjia?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: erjia_user
    password: StSq^2*2@@vTCu%m

  redis:
    host: 47.92.236.83
    port: 26379
    password: 7s=p#]f6.deX
    database: 5

server:
  # 端口
  port: 8886
